services:
 skyscrape:
    image: ghcr.io/iharsh02/skyscrape:latest
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.skyscrape.tls=true"
      - "traefik.http.routers.skyscrape.tls.certresolver=cloudflare"
      - "traefik.http.routers.skyscrape.entrypoints=websecure"
      - "traefik.http.routers.skyscrape.rule=Host(`skyscrape.online`)"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - API_SECRET=${API_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    networks:
      - web-external
    restart: unless-stopped
networks:
  web-external:
    external: true